//
//  ReactionsModalViewController.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 17/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class ReactionsModalViewController: UIViewController, ReactionsModalViewProtocol {

	var presenter: ReactionsModalPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet public var collectionView: UICollectionView!
    @IBOutlet public weak var viewPanIndicator: UIView!
    @IBOutlet public var tableView: UITableView! {
        didSet {
            tableView.tableFooterView = UIView()
        }
        
    }
    
    @IBOutlet weak var viewContainer: UIView!
    
    //MARK: - Properties
    public var postsReactionsCopy: PostReactions?
    public var postId = Int()
    public var skip = 0
    
    public var postReactionsHeaders: Headers? {
        didSet {
            collectionView.reloadData()
        }
    }
    
    public var postsReactions: PostReactions? {
        didSet {
            tableView.reloadData()
        }
    }

    //MARK: - Life cycle
	override public func viewDidLoad() {
        super.viewDidLoad()
        
        setUpView()
        presenter?.getPostsReactions(postId: postId)
    }
    
    public override func viewWillAppear(_ animated: Bool) {
        print("VC ECNews - RectionsModalVC ")
    }
    
    //MARK: - Methods
    private func setUpView() {
        
        viewPanIndicator.setCorner(cornerRadius: 2)
        
        collectionView.dataSource = self
        collectionView.delegate = self
        collectionView.register(UINib(nibName: "ReactionsInfoCVC",bundle: Bundle(for: ReactionsInfoCVC.self)), forCellWithReuseIdentifier: "ReactionsInfoCVC")
        
        tableView.prefetchDataSource = self
        tableView.dataSource = self
        tableView.delegate = self
        tableView.separatorStyle = .none
        tableView.register(UINib(nibName: "ReactionsMoreInfoTVC", bundle: Bundle(for: ReactionsMoreInfoTVC.self)), forCellReuseIdentifier: "ReactionsMoreInfoTVC")
    }
    
    func didFinishGettingPostsReactions(reactions: PostReactions) {
        if postsReactions != nil {
            postsReactionsCopy?.data.resp.append(contentsOf: reactions.data.resp)
            postsReactions?.data.resp.append(contentsOf: reactions.data.resp)
            postReactionsHeaders?.append(contentsOf: reactions.data.header)
        } else {
            postReactionsHeaders = reactions.data.header
            postsReactionsCopy = reactions
            postsReactions = reactions
        }
    }
    
    func didFinishGettingPostsWithErrors(error: SocialNetworkErrors) {
        print(error.message)
    }

}
