//
//  ReactionsModalRouter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 17/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class ReactionsModalRouter: ReactionsModalWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ReactionsModalViewController(nibName: "ReactionsModalViewController", bundle:  Bundle(for: ReactionsModalViewController.self))
        let interactor = ReactionsModalInteractor()
        let router = ReactionsModalRouter()
        let presenter = ReactionsModalPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
