//
//  ReactionsModalInteractor.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 17/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Alamofire

public struct ReactionsGetInPublication: Codable {
    let post_id: Int
    let skip: Int
    let limit: Int
    let FIIDEMPLEADO: Int
}

public class ReactionsModalInteractor: ReactionsModalInteractorProtocol {

    weak var presenter: ReactionsModalPresenterProtocol?
    
    //MARK: - Properties
    private var snService = SocialNetworkService()
    
    //MARK: - PostsReactions
    func getPostsReactions(postId: Int) {
        let params = ReactionsGetInPublication(post_id: postId,
                                               skip: 0,
                                               limit: 10,
                                               FIIDEMPLEADO: SocialNetworkConstant.shared.userId)
        
        let request = snService.getRequestWP(method: .getInPublication, params: params)
        snService.makeRequest(request: request) { (data, error) in
            if let error = error {
                self.presenter?.didFinishGettingPostsWithErrors(error: error)
            } else {
                do {
                    let result = try JSONDecoder().decode(PostReactions.self, from: data!)
                    self.presenter?.didFinishGettingPostsReactions(reactions: result)
                } catch {
                    self.presenter?.didFinishGettingPostsWithErrors(error: SocialNetworkErrors.ResponseError)
                }
            }
        }
    }
}
