//
//  ReactionsModalPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 17/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class ReactionsModalPresenter: ReactionsModalPresenterProtocol {

    weak private var view: ReactionsModalViewProtocol?
    var interactor: ReactionsModalInteractorProtocol?
    private let router: ReactionsModalWireframeProtocol

    init(interface: ReactionsModalViewProtocol, interactor: ReactionsModalInteractorProtocol?, router: ReactionsModalWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - PostsReactions
    func getPostsReactions(postId: Int) {
        interactor?.getPostsReactions(postId: postId)
    }
    
    func didFinishGettingPostsReactions(reactions: PostReactions) {
        view?.didFinishGettingPostsReactions(reactions: reactions)
    }
    
    func didFinishGettingPostsWithErrors(error: SocialNetworkErrors) {
        view?.didFinishGettingPostsWithErrors(error: error)
    }

}
