//
//  InitViewInteractor.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 14/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class InitViewInteractor: InitViewInteractorProtocol {

    weak var presenter: InitViewPresenterProtocol?
    
}
