//
//  InitViewProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 14/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol InitViewWireframeProtocol: class {

}

//MARK: Presenter -
protocol InitViewPresenterProtocol: class {

}

//MARK: Interactor -
protocol InitViewInteractorProtocol: class {
    
    var presenter: InitViewPresenterProtocol?  { get set }
}

//MARK: View -
protocol InitViewViewProtocol: class {
    
    var presenter: InitViewPresenterProtocol?  { get set }
}
