//
//  LibraryResourcesRouter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LibraryResourcesRouter: LibraryResourcesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LibraryResourcesViewController(nibName: "LibraryResourcesViewController", bundle: Bundle.local)
        let interactor = LibraryResourcesInteractor()
        let router = LibraryResourcesRouter()
        let presenter = LibraryResourcesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
