//
//  LibraryResourcesInteractor.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LibraryResourcesInteractor: LibraryResourcesInteractorProtocol {

    weak var presenter: LibraryResourcesPresenterProtocol?
}
