//
//  LibraryResourcesPresenter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LibraryResourcesPresenter: LibraryResourcesPresenterProtocol {

    weak private var view: LibraryResourcesViewProtocol?
    var interactor: LibraryResourcesInteractorProtocol?
    private let router: LibraryResourcesWireframeProtocol

    init(interface: LibraryResourcesViewProtocol, interactor: LibraryResourcesInteractorProtocol?, router: LibraryResourcesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
