//
//  LibraryResourcesProtocols.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LibraryResourcesWireframeProtocol: class {

}
//MARK: Presenter -
protocol LibraryResourcesPresenterProtocol: class {

}

//MARK: Interactor -
protocol LibraryResourcesInteractorProtocol: class {

  var presenter: LibraryResourcesPresenterProtocol?  { get set }
}

//MARK: View -
protocol LibraryResourcesViewProtocol: class {

  var presenter: LibraryResourcesPresenterProtocol?  { get set }
}
