//
//  MassesInformationPresenter.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MassesInformationPresenter: MassesInformationPresenterProtocol {

    weak private var view: MassesInformationViewProtocol?
    var interactor: MassesInformationInteractorProtocol?
    private let router: MassesInformationWireframeProtocol

    init(interface: MassesInformationViewProtocol, interactor: MassesInformationInteractorProtocol?, router: MassesInformationWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
