//
//  MassesInformationProtocols.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MassesInformationWireframeProtocol: class {

}
//MARK: Presenter -
protocol MassesInformationPresenterProtocol: class {

}

//MARK: Interactor -
protocol MassesInformationInteractorProtocol: class {

  var presenter: MassesInformationPresenterProtocol?  { get set }
}

//MARK: View -
protocol MassesInformationViewProtocol: class {

  var presenter: MassesInformationPresenterProtocol?  { get set }
}
