//
//  MassesInformationViewController.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MassesInformationViewController: UIViewController, MassesInformationViewProtocol {

	var presenter: MassesInformationPresenterProtocol?
    
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var IconImg: UIImageView!
    @IBOutlet weak var nameLbl: UILabel!
    @IBOutlet weak var addFavoriteBtn: UIButton!
    @IBOutlet weak var favoriteBtn: UIButton!
    @IBOutlet weak var addressLbl: UILabel!
    @IBOutlet weak var servicesCV: UICollectionView!
    @IBOutlet weak var historyLbl: UILabel!
    
    
	override func viewDidLoad() {
        super.viewDidLoad()
    }

    
    
    //MARK: - Actions
    @IBAction func back(_ sender: Any) {
    }
    
    @IBAction func addFavorite(_ sender: Any) {
    }
    
    @IBAction func removeFavorites(_ sender: Any) {
    }
    
    @IBAction func routeMap(_ sender: Any) {
    }
    
    @IBAction func donate(_ sender: Any) {
    }

}
