//
//  MassesInformationRouter.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class MassesInformationRouter: MassesInformationWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MassesInformationViewController(nibName: "MassesInformationViewController", bundle: Bundle.local)
        let interactor = MassesInformationInteractor()
        let router = MassesInformationRouter()
        let presenter = MassesInformationPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
