//
//  MassesInformationInteractor.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MassesInformationInteractor: MassesInformationInteractorProtocol {

    weak var presenter: MassesInformationPresenterProtocol?
}
