//
//  LocationsProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 06/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreLocation
import MapKit

//MARK: Wireframe -
protocol LocationsWireframeProtocol: class {

}

//MARK: Presenter -
protocol LocationsPresenterProtocol: class {
    
    //MARK: - GetMapImage
    func getMapImage(coordinates: CLLocationCoordinate2D)
    func didFinishGettingMap(image: UIImage?)
    func didFinishGettingMapWithErrors(error: SocialNetworkErrors)
    
}

//MARK: Interactor -
protocol LocationsInteractorProtocol: class {
    
    var presenter: LocationsPresenterProtocol?  { get set }
    
    //MARK: - GetMapImage
    func getMapImage(coordinates: CLLocationCoordinate2D)
}

//MARK: View -
protocol LocationsViewProtocol: class {
    
    var presenter: LocationsPresenterProtocol?  { get set }
    
    //MARK: - GetMapImage
    func didFinishGettingMap(image: UIImage?)
    func didFinishGettingMapWithErrors(error: SocialNetworkErrors)
}
