//
//  LocationsPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 06/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreLocation
import MapKit

public class LocationsPresenter: LocationsPresenterProtocol {

    weak private var view: LocationsViewProtocol?
    var interactor: LocationsInteractorProtocol?
    private let router: LocationsWireframeProtocol

    init(interface: LocationsViewProtocol, interactor: LocationsInteractorProtocol?, router: LocationsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - GetMapImage
    func getMapImage(coordinates: CLLocationCoordinate2D) {
        interactor?.getMapImage(coordinates: coordinates)
    }
    
    func didFinishGettingMap(image: UIImage?) {
        view?.didFinishGettingMap(image: image)
    }
    
    func didFinishGettingMapWithErrors(error: SocialNetworkErrors) {
        view?.didFinishGettingMapWithErrors(error: error)
    }
    
}
