//
//  LibraryDescriptionRouter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LibraryDescriptionRouter: LibraryDescriptionWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LibraryDescriptionViewController(nibName: "LibraryDescriptionViewController", bundle: Bundle.local)
        let interactor = LibraryDescriptionInteractor()
        let router = LibraryDescriptionRouter()
        let presenter = LibraryDescriptionPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
