//
//  LibraryDescriptionViewController.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Lottie

class LibraryDescriptionViewController: UIViewController, LibraryDescriptionViewProtocol {
    
    @IBOutlet weak var txtDescription: UITextView! 
    
    var presenter: LibraryDescriptionPresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        NotificationCenter.default.addObserver(self, selector: #selector(loadDescription(notification:)), name: Notification.Name(rawValue: "loadDescription"), object: nil)
    }
    
    @objc func loadDescription(notification: NSNotification){
        let contentDescription = notification.object as? String
        txtDescription.text = contentDescription
    }
    
}
