//
//  LibraryDescriptionProtocols.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LibraryDescriptionWireframeProtocol: class {

}
//MARK: Presenter -
protocol LibraryDescriptionPresenterProtocol: class {

}

//MARK: Interactor -
protocol LibraryDescriptionInteractorProtocol: class {

  var presenter: LibraryDescriptionPresenterProtocol?  { get set }
}

//MARK: View -
protocol LibraryDescriptionViewProtocol: class {

  var presenter: LibraryDescriptionPresenterProtocol?  { get set }
}
