//
//  LibraryDescriptionPresenter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LibraryDescriptionPresenter: LibraryDescriptionPresenterProtocol {

    weak private var view: LibraryDescriptionViewProtocol?
    var interactor: LibraryDescriptionInteractorProtocol?
    private let router: LibraryDescriptionWireframeProtocol

    init(interface: LibraryDescriptionViewProtocol, interactor: LibraryDescriptionInteractorProtocol?, router: LibraryDescriptionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
