//
//  CreatePostRouter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Diego Martinez on 01/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class CreatePostRouter: CreatePostWireframeProtocol {

    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        
        
        let view = CreatePostViewController(nibName: "CreatePostViewController", bundle: Bundle(identifier: "mx.arquidiocesis.EncuentroCatolicoNews"))
        
        let interactor = CreatePostInteractor()
        let router = CreatePostRouter()
        let presenter = CreatePostPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    
    
}

public class SNCommenctsRoute: RSCommentsWireframeProtocol{
    
    weak var viewController: UIViewController?
    
    static func createNewModule() -> UIViewController{
        let view = CommentsViewController(nibName: "CommentsViewController", bundle: Bundle(identifier: "mx.arquidiocesis.EncuentroCatolicoNews"))
        let interacto = RSCommentsInteractor()
        let router = SNCommenctsRoute()
        let presenter = RSCommentsPresenter(interface: view, interactor: interacto, router: router)
        
        view.presenter = presenter
        interacto.presenter = presenter
        router.viewController = view
        return view
    }
}
