//
//  SacramentsProtocols.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 30/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SacramentsWireframeProtocol: class {

}
//MARK: Presenter -
protocol SacramentsPresenterProtocol: class {
    func getSacraments()
    func getResponse(errores: ServerErrors, data: Sacraments)
}

//MARK: Interactor -
protocol SacramentsInteractorProtocol: class {
    var presenter: SacramentsPresenterProtocol?  { get set }
    func requestSacraments()
}

//MARK: View -
protocol SacramentsViewProtocol: class {
  var presenter: SacramentsPresenterProtocol?  { get set }
    func mostrarMSG(dtcAlerta: [String:String])
    func loadOptions(data: Sacraments)
}
