//
//  SacramentsPresenter.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 30/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SacramentsPresenter: SacramentsPresenterProtocol {
    weak private var view: SacramentsViewProtocol?
    var interactor: SacramentsInteractorProtocol?
    private let router: SacramentsWireframeProtocol

    init(interface: SacramentsViewProtocol, interactor: SacramentsInteractorProtocol?, router: SacramentsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getSacraments() {
        interactor?.requestSacraments()
    }
    
    func getResponse(errores: ServerErrors, data: Sacraments) {
        DispatchQueue.main.async {
            switch errores {
            case .ErrorInterno:
                let msg = ["titulo":"Error", "cuerpo": "Error en el servidor"]
                self.view?.mostrarMSG(dtcAlerta: msg)
            case .ErrorServidor:
                let msg = ["titulo":"Error", "cuerpo": "Error en la aplicación"]
                self.view?.mostrarMSG(dtcAlerta: msg)
            case .OK:
                self.view?.loadOptions(data: data)
            }
        }
    }

}
