//
//  LibraryAndResourcesRouter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class LibraryAndResourcesRouter: LibraryAndResourcesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule(contentID: Int) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LibraryAndResourcesViewController(nibName: "LibraryAndResourcesViewController", bundle: Bundle.local)
        let interactor = LibraryAndResourcesInteractor()
        let router = LibraryAndResourcesRouter()
        let presenter = LibraryAndResourcesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.contentID = contentID
        
        return view
    }
}
