//
//  LibraryAndResourcesProtocols.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 15/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LibraryAndResourcesWireframeProtocol: class {

}
//MARK: Presenter -
protocol LibraryAndResourcesPresenterProtocol: class {
    func getContentByID(contentID: Int)
    func getResponse(errores: ServerErrors, data: ContentDetail?)
}

//MARK: Interactor -
protocol LibraryAndResourcesInteractorProtocol: class {

  var presenter: LibraryAndResourcesPresenterProtocol?  { get set }
    func requestContentDetail(contentID: Int)
}

//MARK: View -
protocol LibraryAndResourcesViewProtocol: class {

   var presenter: LibraryAndResourcesPresenterProtocol?  { get set }
    func mostrarMSG(dtcAlerta: [String:String])
    func loadContentDetail(data: ContentDetail)
}
