//
//  CategoriesProtocols.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 20/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CategoriesWireframeProtocol: class {

}
//MARK: Presenter -
protocol CategoriesPresenterProtocol: class {
    func getContentByCategory(category: String)
    func getContentWithFilter(filter: String)
    func getResponse(errores: ServerErrors, data: LibraryCategories?)
    
}

//MARK: Interactor -
protocol CategoriesInteractorProtocol: class {
  var presenter: CategoriesPresenterProtocol?  { get set }
    func requestContentByCategory(category: String)
    func requestContentWithFilter(filter: String)
}

//MARK: View -
protocol CategoriesViewProtocol: class {

  var presenter: CategoriesPresenterProtocol?  { get set }
    func mostrarMSG(dtcAlerta: [String:String])
    func loadContentByCategory(data: LibraryCategories)
}
