//
//  FeelingsPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 14/12/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class FeelingsPresenter: FeelingsPresenterProtocol {

    weak private var view: FeelingsViewProtocol?
    var interactor: FeelingsInteractorProtocol?
    private let router: FeelingsWireframeProtocol

    init(interface: FeelingsViewProtocol, interactor: FeelingsInteractorProtocol?, router: FeelingsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
        //MARK: - Feelings
    func getFeelings() {
        interactor?.getFeelings()
    }
    
    func didFinishGettingFeelings(feelings: Feelings) {
        view?.didFinishGettingFeelings(feelings: feelings)
    }
    
    func didFinishGettingFeelingsWithErrors(error: SocialNetworkErrors) {
        view?.didFinishGettingFeelingsWithErrors(error: error)
    }

}
