//
//  FeelingsProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 14/12/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FeelingsWireframeProtocol: class {

}

//MARK: Presenter -
protocol FeelingsPresenterProtocol: class {

    //MARK: - Feelings
    func getFeelings()
    func didFinishGettingFeelings(feelings: Feelings)
    func didFinishGettingFeelingsWithErrors(error: SocialNetworkErrors)
}

//MARK: Interactor -
protocol FeelingsInteractorProtocol: class {
    
    var presenter: FeelingsPresenterProtocol?  { get set }
    
    //MARK: - Feelings
    func getFeelings()
}

//MARK: View -
protocol FeelingsViewProtocol: class {
    
    var presenter: FeelingsPresenterProtocol?  { get set }
    
    //MARK: - Feelings
    func didFinishGettingFeelings(feelings: Feelings)
    func didFinishGettingFeelingsWithErrors(error: SocialNetworkErrors)
}
