//
//  ScheduleMassTimeProtocols.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 28/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ScheduleMassTimeWireframeProtocol: class {
    func nextFlowPayment()
}
//MARK: Presenter -
protocol ScheduleMassTimePresenterProtocol: class {
    func sendService(date: String, hour: String, description: String, location: Int, service_id: Int, mention_from: String)
    func getResponse(errores: ServerErrors, data: ServicesResponse?)
    func requestCatalogIntentions()
    func succesGetCatalog(data: [CatalogIntentions])
    func failGetCatalgo()
    func requestGetHours(locationID: String, dateStr: String)
    func successGetHours(data: [ListIntentions2])
    func failGetHours()
    func nextFlowPayment()
        
        
}

//MARK: Interactor -
protocol ScheduleMassTimeInteractorProtocol: class {

  var presenter: ScheduleMassTimePresenterProtocol?  { get set }
    func sendService(date: String, hour: String, description: String, location: Int, service_id: Int,mention_from: String)
    func getCatalog()
    func getListIntetions(locationID: String, dateStr: String)
}

//MARK: View -
protocol ScheduleMassTimeViewProtocol: class {

  var presenter: ScheduleMassTimePresenterProtocol?  { get set }
    func loadResult(data: ServicesResponse)
    func mostrarMSG(dtcAlerta: [String : String])
    func succesCatalog(data: [CatalogIntentions])
    func failCatalog()
    func successHours(data: [ListIntentions2])
    func failHours()
    
}
