//
//  ScheduleMassTimeRouter.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 28/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScheduleMassTimeRouter: ScheduleMassTimeWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(date: Date, location: Assigned) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ScheduleMassTimeViewController(nibName: "ScheduleMassTimeViewController", bundle: Bundle.init(identifier: "mx.arquidiocesis.EncuentroCatolicoServices"))
        let interactor = ScheduleMassTimeInteractor()
        let router = ScheduleMassTimeRouter()
        let presenter = ScheduleMassTimePresenter(interface: view, interactor: interactor, router: router)
        
        view.maseDate = date
        view.location = location
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
