//
//  VirtualViewController.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Diego Martinez on 25/02/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VirtualViewController: UIViewController, VirtualViewProtocol {
    
	var presenter: VirtualPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
