//
//  VirtualRouter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Diego Martinez on 25/02/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class VirtualRouter: VirtualWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = VirtualViewController(nibName: "VirtualViewController", bundle: Bundle.local)
        let interactor = VirtualInteractor()
        let router = VirtualRouter()
        let presenter = VirtualPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
