//
//  VirtualPresenter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Diego Martinez on 25/02/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VirtualPresenter: VirtualPresenterProtocol {

    weak private var view: VirtualViewProtocol?
    var interactor: VirtualInteractorProtocol?
    private let router: VirtualWireframeProtocol

    init(interface: VirtualViewProtocol, interactor: VirtualInteractorProtocol?, router: VirtualWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
