//
//  OtherServicesRouter.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 22/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class OtherServicesRouter: OtherServicesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = OtherServicesViewController(nibName: "OtherServicesViewController", bundle: Bundle.init(identifier: "mx.arquidiocesis.EncuentroCatolicoServices"))
        let interactor = OtherServicesInteractor()
        let router = OtherServicesRouter()
        let presenter = OtherServicesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
