//
//  OtherServicesProtocols.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 22/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol OtherServicesWireframeProtocol: class {

}
//MARK: Presenter -
protocol OtherServicesPresenterProtocol: class {
    func getOptions(type: cases)
    func getResponse(errores: ServerErrors, data: [servicesSubOption], type: cases)
}

//MARK: Interactor -
protocol OtherServicesInteractorProtocol: class {
  var presenter: OtherServicesPresenterProtocol?  { get set }
    func requestServices(type: cases)
}

//MARK: View -
protocol OtherServicesViewProtocol: class {
  var presenter: OtherServicesPresenterProtocol?  { get set }
    func mostrarMSG(dtcAlerta: [String:String])
    func loadOptions(data: [servicesSubOption], type: cases)
}
