//
//  PaymentRouter.swift
//  zeus-ios-sdk-payment
//
//  Created Gabriel Briseño on 06/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PaymentRouter: PaymentWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PaymentViewController(nibName: nil, bundle: nil)
        let interactor = PaymentInteractor()
        let router = PaymentRouter()
        let presenter = PaymentPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
