//
//  PaymentProtocols.swift
//  zeus-ios-sdk-payment
//
//  Created Gabriel Briseño on 06/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PaymentWireframeProtocol: class {

}
//MARK: Presenter -
protocol PaymentPresenterProtocol: class {
    func makeDonativeFor(quantity: Double, forAccount: String)
    func didFinishWithSuccess()
    func didFinishWith(error: String)
}

//MARK: Interactor -
protocol PaymentInteractorProtocol: class {

    var presenter: PaymentPresenterProtocol?  { get set }
    func makeDonativeFor(quantity: Double, forAccount: String)
}

//MARK: View -
protocol PaymentViewProtocol: class {

    var presenter: PaymentPresenterProtocol?  { get set }
    func didFinishWithSuccess()
    func didFinishWith(error: String)
}
