//
//  PaymentPresenter.swift
//  zeus-ios-sdk-payment
//
//  Created Gabriel Briseño on 06/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PaymentPresenter: PaymentPresenterProtocol {
    weak private var view: PaymentViewProtocol?
    var interactor: PaymentInteractorProtocol?
    private let router: PaymentWireframeProtocol

    init(interface: PaymentViewProtocol, interactor: PaymentInteractorProtocol?, router: PaymentWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func makeDonativeFor(quantity: Double, forAccount: String) {
        interactor?.makeDonativeFor(quantity: quantity, forAccount: forAccount)
    }
       
    func didFinishWithSuccess() {
        
    }
       
    func didFinishWith(error: String) {
        view?.didFinishWith(error: error)
    }
       
}
