//
//  FeedProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 01/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RealmSwift

//MARK: Wireframe -
protocol FeedWireframeProtocol: class {
    
    //MARK: - ShowPostDetail
    func showPostDetail(navController: UINavigationController?, post: PublicationRealm)
    
    //MARK: - ShowComments
//    func showComments(postId: Int)
    
    //MARK: - ShowWhoPublishes
//    func showWhoPublishes()
    
    //MARK: - ShowEditPost
//    func showEditPost(postId: Int, content: String, nombreGrupo: String, imagenGrupo: String)
}

//MARK: Presenter -
protocol FeedPresenterProtocol: class {

    //MARK: - Posts
    func getPosts(isFromPage: Bool)
    func didFinishGettingPosts(isFromPage: Bool)
    func didFinishGettingPostsWithErrors(error: SocialNetworkErrors)
    
    //MARK: - Watch
//    func watchPost(postId: Int)
    
    //MARK: - ShowPostDetail
    func showPostDetail(navController: UINavigationController?, post: PublicationRealm)
    
    //MARK: - ShowComments
//    func showComments(postId: Int)
    
    //MARK: - ShowWhoPublishes
//    func showWhoPublishes()
    
    //MARK: - ShowEditPost
//    func showEditPost(postId: Int, content: String, nombreGrupo: String, imagenGrupo: String)
    
    //MARK: - Notifications
    func createObserver(userId: Int)
    func didFinishGettingNotifications(notificationsCount: String?)
}

//MARK: Interactor -
protocol FeedInteractorProtocol: class {
    
    var presenter: FeedPresenterProtocol?  { get set }
    
    //MARK: - Posts
    func getPosts(isFromPage: Bool)
    
    //MARK: - Watch
//    func watchPost(postId: Int)
    
    //MARK: - Notifications
    func createObserver(userId: Int)
}

//MARK: View -
protocol FeedViewProtocol: class {
    
    var presenter: FeedPresenterProtocol?  { get set }
    
    //MARK: - Posts
    func didFinishGettingPosts(isFromPage: Bool)
    func didFinishGettingPostsWithErrors(error: SocialNetworkErrors)
    
    //MARK: - Notifications
    func didFinishGettingNotifications(notificationsCount: String?)
}
