//
//  ChurchesListPresenter.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 23/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChurchesListPresenter: ChurchesListPresenterProtocol {

    weak private var view: ChurchesListViewProtocol?
    var interactor: ChurchesListInteractorProtocol?
    private let router: ChurchesListWireframeProtocol

    init(interface: ChurchesListViewProtocol, interactor: ChurchesListInteractorProtocol?, router: ChurchesListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getChurches(requestType: String, latitude: Double, longitude: Double) {
        interactor?.requestChurchLocations(type: requestType, latitude: latitude, longitude: longitude)
    }
    
    func getResponse(errores: ServerErrors, data: ChurchLocations) {
        DispatchQueue.main.async {
            switch errores {
            case .ErrorInterno:
                let msg = ["titulo":"Error", "cuerpo": "Error en el servidor"]
                self.view?.mostrarMSG(dtcAlerta: msg)
            case .ErrorServidor:
                let msg = ["titulo":"Error", "cuerpo": "Error en la aplicación"]
                self.view?.mostrarMSG(dtcAlerta: msg)
            case .OK:
                self.view?.loadChurches(data: data)
            }
        }
    }
    
}
