//
//  ChurchesListProtocols.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 23/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ChurchesListWireframeProtocol: class {

}
//MARK: Presenter -
protocol ChurchesListPresenterProtocol: class {
    func getChurches(requestType: String, latitude: Double, longitude: Double)
    func getResponse(errores: ServerErrors, data: ChurchLocations)
}

//MARK: Interactor -
protocol ChurchesListInteractorProtocol: class {
    var presenter: ChurchesListPresenterProtocol?  { get set }
    func requestChurchLocations(type: String, latitude: Double, longitude: Double)
}

//MARK: View -
protocol ChurchesListViewProtocol: class {
    var presenter: ChurchesListPresenterProtocol?  { get set }
    func mostrarMSG(dtcAlerta: [String:String])
    func loadChurches(data: ChurchLocations)
}
