//
//  ChurchesListRouter.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 23/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class ChurchesListRouter: ChurchesListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ChurchesListViewController(nibName: "ChurchesListViewController", bundle: Bundle.init(identifier: "mx.arquidiocesis.EncuentroCatolicoServices"))
        let interactor = ChurchesListInteractor()
        let router = ChurchesListRouter()
        let presenter = ChurchesListPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
