//
//  MassesListProtocols.swift
//  EncuentroCatolicoMyChurch
//
//  Created Desarrollo on 07/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MassesListWireframeProtocol: class {

}
//MARK: Presenter -
protocol MassesListPresenterProtocol: class {
    func getChurches(name: String)
    func getResponse(errores: ServerErrors, data: ChurchesMasses)
}

//MARK: Interactor -
protocol MassesListInteractorProtocol: class {
  var presenter: MassesListPresenterProtocol?  { get set }
    func requestChurches(name: String)
}

//MARK: View -
protocol MassesListViewProtocol: class {
  var presenter: MassesListPresenterProtocol?  { get set }
    func mostrarMSG(dtcAlerta: [String:String])
    func loadChurches(data: ChurchesMasses)
}
