//
//  MassesListPresenter.swift
//  EncuentroCatolicoMyChurch
//
//  Created Desarrollo on 07/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MassesListPresenter: MassesListPresenterProtocol {

    weak private var view: MassesListViewProtocol?
    var interactor: MassesListInteractorProtocol?
    private let router: MassesListWireframeProtocol

    init(interface: MassesListViewProtocol, interactor: MassesListInteractorProtocol?, router: MassesListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getResponse(errores: ServerErrors, data: ChurchesMasses) {
        DispatchQueue.main.async {
            switch errores {
            case .ErrorInterno:
                let msg = ["titulo":"Error", "cuerpo": "Error en el servidor"]
                self.view?.mostrarMSG(dtcAlerta: msg)
            case .ErrorServidor:
                let msg = ["titulo":"Error", "cuerpo": "Error en la aplicación"]
                self.view?.mostrarMSG(dtcAlerta: msg)
            case .OK:
                self.view?.loadChurches(data: data)
            }
        }
    }
    
    func getChurches(name: String) {
        interactor?.requestChurches(name: name)
    }

}
