//
//  MassesListRouter.swift
//  EncuentroCatolicoMyChurch
//
//  Created Desarrollo on 07/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class MassesListRouter: MassesListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MassesListViewController(nibName: "MassesListViewController", bundle: Bundle.init(identifier: "mx.arquidiocesis.EncuentroCatolicoMyChurch"))
        let interactor = MassesListInteractor()
        let router = MassesListRouter()
        let presenter = MassesListPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
