//
//  DetailPostInteractor.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 06/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Alamofire

public class DetailPostInteractor: DetailPostInteractorProtocol {

    weak var presenter: DetailPostPresenterProtocol?
    
    //MARK: - Properties
    private var snService = SocialNetworkService()
    
    //MARK: - TopReactions
    func getTopReactions(postId: Int) {
        let params = ReactionsTop(post_id: postId,
                                      skip: 0,
                                      limit: 5)
        
        let request = snService.getRequestWP(method: .reactionsTop, params: params)
        snService.makeRequest(request: request) { (data, error) in
            if let error = error {
                self.presenter?.didFinishGettingTopReactionsWithErrors(error: error)
            } else {
                 do {
                     guard let allData = data else { return }
                     let result = try JSONDecoder().decode(TopReactions.self, from: allData)
                     self.presenter?.didFinishGettingTopReactions(topReactions: result)
                } catch {
                     self.presenter?.didFinishGettingTopReactionsWithErrors(error: SocialNetworkErrors.ResponseError)
                }
            }
        }
    }
    
}


public struct ReactionsTop: Codable {
    let post_id: Int
    let skip: Int
    let limit: Int
}
