//
//  HomeProtocols.swift
//  EncuentroCatolicoHome
//
//  Created Diego Martinez on 23/02/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {
}

//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {
    func cargarDatosUsuario()
    func obtieneRespuetaUsuario(errores: ErroresServidorHome, user: UserRespHome?)
    func abrirBancoAppParaApoyar(mount: String)
    func requestUserDetail()
    func responseGetProfile(responseCode: HTTPURLResponse, dataResponse: ProfileDetailImgH)
    func requestHomeData(type: String, date: String)
    func trasportResponseHome(response: HTTPURLResponse, data: [HomePosts])
    func requestSuggestions(type: String)
    func transportResponsePosts(response: HTTPURLResponse, data: [HomePosts])
    func transportResponseSuggestions(response: HTTPURLResponse, data: [HomeSuggestions])
    func requestStreaming()
    func onSuccessStreaming(data: [LiveModel], response: HTTPURLResponse)
    func onFailStreaming(message: Error)
    func onFailCarrusel(type: String)
        
}

//MARK: Interactor -
protocol HomeInteractorProtocol: AnyObject {

    var presenter: HomePresenterProtocol?  { get set }
    func cargarDatosPersona()
    func getUserDetail()
    func getSaintOfDay(type: String, date: String)
    func getSuggestions(type: String)
    func requestSrtreaming()
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {

    var presenter: HomePresenterProtocol?  { get set }
    func mostrarInfo(dtcAlerta: [String:String]?, user: UserRespHome?)
    func successLoadImg(dataResponse: ProfileDetailImgH)
  //  func validateCommunityStatus(dataResponse: ProfileDetailImgH)
    func failLoadImg()
    func validateCommunityStatus(dataResponse: ProfileDetailImgH)
    func succesGetHome(data: [HomePosts])
    func failGetHome(message: String)
    func onSuccessGetSuggestions(data: [HomeSuggestions])
    func onSuccessGetPosts(data: [HomePosts])
    func onFialGetSuggestions(message: String)
    func successStreaming(data: [LiveModel])
    func failStreaming(message: String)
    func onFailCarruselV(type: String)
}
