//
//  EditImagesRouter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 12/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

//import UIKit
//
//public class EditImagesRouter: EditImagesWireframeProtocol {
//    
//    weak var viewController: UIViewController?
//    
//    static func createModule() -> UIViewController {
//        // Change to get view from storyboard if not using progammatic UI
//        let view = EditImagesViewController(nibName: "EditImagesViewController", bundle: Bundle.local)
//        let interactor = EditImagesInteractor()
//        let router = EditImagesRouter()
//        let presenter = EditImagesPresenter(interface: view, interactor: interactor, router: router)
//        
//        view.presenter = presenter
//        interactor.presenter = presenter
//        router.viewController = view
//        
//        return view
//    }
//}
