////
////  EditImagesViewController.swift
////  zeus-ios-sdk-new-social-network
////
////  Created Miguel Angel Vicario Flores on 12/10/20.
////  Copyright © 2020 Gabriel Briseño. All rights reserved.
////
////  Template generated by Juanpe Catalán @JuanpeCMiOS
////
//
//import UIKit
//import Photos
//
//public protocol EditImagesDelegate: class {
//    func saveImages(media: [MediaData])
//}
//
//public class EditImagesViewController: UIViewController, EditImagesViewProtocol {
//
//	var presenter: EditImagesPresenterProtocol?
//
//    //MARK: - @IBOutlets
//    @IBOutlet public weak var tableView: UITableView! {
//        didSet { tableView.tableFooterView = UIView() }
//    }
//
//    //MARK: - Properties
//    public weak var delegate: EditImagesDelegate?
//    public var media = [MediaData]()
//
//    //MARK: - Life cycle
//	override public func viewDidLoad() {
//        super.viewDidLoad()
//
//        setUpView()
//    }
//
//    //MARK: - Methods
//    private func setUpView() {
//        tableView.dataSource = self
//        tableView.delegate = self
//        tableView.separatorStyle = .none
//        tableView.rowHeight = tableView.frame.width
//        tableView.keyboardDismissMode = .onDrag
//        tableView.register(UINib(nibName: "EditImagesTVC", bundle: Bundle.local), forCellReuseIdentifier: "EditImagesTVC")
//        tableView.register(UINib(nibName: "AddMoreImagesTVC", bundle: Bundle.local), forCellReuseIdentifier: "AddMoreImagesTVC")
//        tableView.register(UINib(nibName: "EditVideosTVC", bundle: Bundle.local), forCellReuseIdentifier: "EditVideosTVC")
//    }
//
//    @objc public func deleteLocation(_ sender: UIButton) {
//        media.remove(at: sender.tag)
//        tableView.reloadData()
//    }
//
//    //MARK: - Actions
//    @objc func addMoreImages(_ sender: UIButton) {
//        let vc = ImagePickerViewController() as ImagePickerController
//        vc.delegate = self
//        vc.modalPresentationStyle = .fullScreen
//        self.present(vc, animated: true)
//    }
//
//    @IBAction func ready(_ sender: UIBarButtonItem) {
//        delegate?.saveImages(media: media)
//        self.dismiss(animated: true, completion: nil)
//    }
//
//    @IBAction func dismiss(_ sender: UIBarButtonItem) {
//        self.dismiss(animated: true, completion: nil)
//    }
//
//}
//
////MARK: - UITableViewDataSource
//extension EditImagesViewController: UITableViewDataSource {
//    public func numberOfSections(in tableView: UITableView) -> Int {
//        return 2
//    }
//
//    public func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
//        switch section {
//        case 0:
//            return media.count
//        default:
//            return 1
//        }
//    }
//
//    public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
//        switch indexPath.section {
//        case 0:
//            if media[indexPath.row].videoURL != nil {
//                let cell = tableView.dequeueReusableCell(withIdentifier: "EditVideosTVC", for: indexPath) as! EditVideosTVC
//
//                cell.videoURL = media[indexPath.row].videoURL
//
//                cell.deleteButton.tag = indexPath.row
//                cell.deleteButton.addTarget(self, action: #selector(deleteLocation), for: .touchUpInside)
//
//                cell.delegate = self
//
//                return cell
//            } else {
//                let cell = tableView.dequeueReusableCell(withIdentifier: "EditImagesTVC", for: indexPath) as! EditImagesTVC
//
//                cell.contentImage.image = media[indexPath.row].image
//
//                cell.deleteButton.tag = indexPath.row
//                cell.deleteButton.addTarget(self, action: #selector(deleteLocation), for: .touchUpInside)
//
//                return cell
//            }
//        default:
//            let cell = tableView.dequeueReusableCell(withIdentifier: "AddMoreImagesTVC", for: indexPath) as! AddMoreImagesTVC
//            cell.addMoreImagesButton.addTarget(self, action: #selector(addMoreImages), for: .touchUpInside)
//            return cell
//        }
//
//    }
//
//}
//
////MARK: - UITableViewDelegate
//extension EditImagesViewController: UITableViewDelegate {
//    public func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
//        switch indexPath.section {
//        case 0:
//            return 300
//        default:
//            return 90
//        }
//    }
//}
//
////MARK: - ImagePickerControllerDelegate
//extension EditImagesViewController: ImagePickerControllerDelegate {
//    public func imagePickerController(_ picker: ImagePickerController, shouldLaunchCameraWithAuthorization status: AVAuthorizationStatus) -> Bool {
//        return true
//    }
//
//    public func imagePickerController(_ picker: ImagePickerController, didFinishPickingImageAssets assets: [PHAsset]) {
//        assets.getData { (media) in
//            self.media.append(contentsOf: media)
//            self.tableView.reloadData()
//            picker.dismiss(animated: true, completion: nil)
//        }
//    }
//
//    public func imagePickerControllerDidCancel(_ picker: ImagePickerController) {
//        picker.dismiss(animated: true, completion: nil)
//    }
//
//}
//
//extension EditImagesViewController: EditVideosDelegate {
//    public func presentFullScreenVideo(videoURL: URL?) {
//        let vc = VideoPresenterRouter.createModule() as! VideoPresenterViewController
//        vc.videoURL = videoURL
//        self.present(vc, animated: true)
//    }
//}
