//
//  EditImagesPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 12/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class EditImagesPresenter: EditImagesPresenterProtocol {

    weak private var view: EditImagesViewProtocol?
    var interactor: EditImagesInteractorProtocol?
    private let router: EditImagesWireframeProtocol

    init(interface: EditImagesViewProtocol, interactor: EditImagesInteractorProtocol?, router: EditImagesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
