//
//  EditImagesProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 12/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol EditImagesWireframeProtocol: class {

}

//MARK: Presenter -
protocol EditImagesPresenterProtocol: class {

}

//MARK: Interactor -
protocol EditImagesInteractorProtocol: class {
    
    var presenter: EditImagesPresenterProtocol?  { get set }
}

//MARK: View -
protocol EditImagesViewProtocol: class {
    
    var presenter: EditImagesPresenterProtocol?  { get set }
}
