//
//  FilterAlertPresenter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 16/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FilterAlertPresenter: FilterAlertPresenterProtocol {

    weak private var view: FilterAlertViewProtocol?
    var interactor: FilterAlertInteractorProtocol?
    private let router: FilterAlertWireframeProtocol

    init(interface: FilterAlertViewProtocol, interactor: FilterAlertInteractorProtocol?, router: FilterAlertWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
