//
//  FilterAlertRouter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 16/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class FilterAlertRouter: FilterAlertWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FilterAlertViewController(nibName: "FilterAlertViewController", bundle: Bundle.local)
        let interactor = FilterAlertInteractor()
        let router = FilterAlertRouter()
        let presenter = FilterAlertPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
