//
//  FilterAlertProtocols.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 16/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FilterAlertWireframeProtocol: class {

}
//MARK: Presenter -
protocol FilterAlertPresenterProtocol: class {

}

//MARK: Interactor -
protocol FilterAlertInteractorProtocol: class {

  var presenter: FilterAlertPresenterProtocol?  { get set }
}

//MARK: View -
protocol FilterAlertViewProtocol: class {

  var presenter: FilterAlertPresenterProtocol?  { get set }
}
