//
//  FilterAlertInteractor.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 16/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FilterAlertInteractor: FilterAlertInteractorProtocol {

    weak var presenter: FilterAlertPresenterProtocol?
}
