//
//  FeedPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 01/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RealmSwift

public class FeedPresenter: FeedPresenterProtocol {
    func getDeletePost(str: String) {
        interactor?.getDeletePost(str: str)
    }
    
    weak private var view: FeedViewProtocol?
    var interactor: FeedInteractorProtocol?
    private let router: FeedWireframeProtocol

    init(interface: FeedViewProtocol, interactor: FeedInteractorProtocol?, router: FeedWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - Posts
    // GGG Timeline
    func getNewPosts(isFromPage: Bool, isRefresh: Bool) {
        interactor?.getNewPosts(isFromPage: isFromPage, isRefresh: isRefresh)
    }
    
    func getFollowed(snId:Int){
        interactor?.getFollowed(snId:snId)
    }
    
    func getFollowsError(error: SocialNetworkErrors){
        print("ES EL ERROR FOLLOWS")
        print(error)
        view?.getFollowsServiceError(error:error)
    }
    
    func getFollowsResponse(with response: ResponseFollowers?, hasMore: Bool) {
        var arrFollowers: [Followers] = []
        guard let response = response else {
            view?.getArrFollows(followeds: arrFollowers, hasMore:hasMore)
            return
        }

        for users in response.result.Follows{
            let follower = Followers(image: users.image, name: users.name, isFollow: knowIfIFollow(status: users.relationshipStatus), userId: users.id, entityId: users.relationshipId, entityType: EntitiesType(rawValue: users.type)?.intValue ?? 1)
            arrFollowers.append(follower)
        }
        
        view?.getArrFollows(followeds: arrFollowers, hasMore:hasMore)
    }
    
    func getNewPostPagin(isFromPage: Bool, posts: [Posts], nxtPag: String) {
        interactor?.getNewPostPagin(isFromPage: isFromPage, posts: posts, nxtPag: nxtPag)
    }
    
    func getPosts(isFromPage: Bool) {
        interactor?.getPosts(isFromPage: isFromPage)
    }
    
    func didFinishGettingPostsWithErrors(error: SocialNetworkErrors) {
        view?.didFinishGettingPostsWithErrors(error: error)
    }
    
    func didFinishGettingPosts(isFromPage: Bool, posts: [Posts]) {
        view?.didFinishGettingPosts(isFromPage: isFromPage, posts: posts)
    }
    
    func knowIfIFollow(status: Int) -> Bool{
        return status == 1 || status == 3
    }
    
    //MARK: - Watch
//    func watchPost(postId: Int) {
//        interactor?.watchPost(postId: postId)
//    }
    
    //MARK: - ShowPostDetail
    func showPostDetail(navController: UINavigationController?, post: PublicationRealm) {
        router.showPostDetail(navController: navController, post: post)
    }
    
    //MARK: - ShowComments
//    func showComments(postId: Int) {
//        router.showComments(postId: postId)
//    }
//
//    //MARK: - ShowEditPost
//    func showEditPost(postId: Int, content: String, nombreGrupo: String, imagenGrupo: String) {
//        router.showEditPost(postId: postId, content: content, nombreGrupo: nombreGrupo, imagenGrupo: imagenGrupo)
//    }
    
    //MARK: - ShowWhoPublishes
    func showNewPost() {
           router.showNewPost()
       }
    
    func showEditPost(post: PublicationRealm, editPost: Bool) {
        // GGG3
        router.showEditPost(post: post, editPost: editPost)
    }
    
    func showNewEditPost(post: Posts, editPost: Bool) {
        router.showNewEditPost(post: post, editPost: editPost)
    }
    
    func showActionsSelected(post: PublicationRealm, strSelected: String) {
        router.showActionsSelected(post: post, strSelected: strSelected)
    }
    
    //MARK: - Notifications
    func createObserver(userId: Int) {
        interactor?.createObserver(userId: userId)
    }
    
    func didFinishGettingNotifications(notificationsCount: String?) {
        view?.didFinishGettingNotifications(notificationsCount: notificationsCount)
    }
}
