//
//  FeedProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 01/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RealmSwift

//MARK: Wireframe -
protocol FeedWireframeProtocol: AnyObject {
    
    //MARK: - ShowPostDetail
    func showPostDetail(navController: UINavigationController?, post: PublicationRealm)
    
    //MARK: - ShowComments
//    func showComments(postId: Int)
    
    //MARK: - ShowNewPost
      func showNewPost()
    
    //MARK: - ShowEditPost
//    func showEditPost(postId: Int, content: String, nombreGrupo: String, imagenGrupo: String)
    func showEditPost(post: PublicationRealm, editPost: Bool)
    func showNewEditPost(post: Posts, editPost: Bool)
    
    //MARK: - ShowComments
    func showActionsSelected(post: PublicationRealm, strSelected: String)
}

//MARK: Presenter -
protocol FeedPresenterProtocol: AnyObject {

    //MARK: - Posts
    // GGG Timeline
    func getNewPosts(isFromPage: Bool, isRefresh: Bool)
    func getNewPostPagin(isFromPage: Bool, posts: [Posts], nxtPag: String)
    func getDeletePost(str: String)
    func getPosts(isFromPage: Bool)
    func didFinishGettingPosts(isFromPage: Bool, posts: [Posts])
    func didFinishGettingPostsWithErrors(error: SocialNetworkErrors)
    //MARK: - Follows
    func getFollowed(snId:Int)
    func getFollowsError(error: SocialNetworkErrors)
    func getFollowsResponse(with response: ResponseFollowers?, hasMore: Bool)
    //MARK: - Watch
//    func watchPost(postId: Int)
    //MARK: - ShowPostDetail
    func showPostDetail(navController: UINavigationController?, post: PublicationRealm)
    
    //MARK: - ShowComments
//    func showComments(postId: Int)
    
    //MARK: - ShowWhoPublishes
    func showNewPost()
    
    //MARK: - ShowEditPost
//    func showEditPost(postId: Int, content: String, nombreGrupo: String, imagenGrupo: String)
    func showEditPost(post: PublicationRealm, editPost: Bool)
    func showNewEditPost(post: Posts, editPost: Bool)
    
    //MARK: - ShowComments
    func showActionsSelected(post: PublicationRealm, strSelected: String)
    
    //MARK: - Notifications
    func createObserver(userId: Int)
    func didFinishGettingNotifications(notificationsCount: String?)
}

//MARK: Interactor -
protocol FeedInteractorProtocol: AnyObject {
    
    var presenter: FeedPresenterProtocol?  { get set }
    
    //MARK: - Posts
    // GGG Timeline
    func getNewPosts(isFromPage: Bool, isRefresh: Bool)
    func getNewPostPagin(isFromPage: Bool, posts: [Posts], nxtPag: String)
    func getDeletePost(str: String)
    func getPosts(isFromPage: Bool)
    func getFollowed(snId:Int)
    //MARK: - Watch
//    func watchPost(postId: Int)
    
    //MARK: - Notifications
    func createObserver(userId: Int)
}

//MARK: View -
protocol FeedViewProtocol: AnyObject {
    
    var presenter: FeedPresenterProtocol?  { get set }
    
    //MARK: - Posts
    func didFinishGettingPosts(isFromPage: Bool, posts: [Posts])
    func didFinishGettingPostsWithErrors(error: SocialNetworkErrors)
    //MARK: - Follows
    func getFollowsServiceError(error: SocialNetworkErrors)
    func getArrFollows(followeds: [Followers], hasMore:Bool)
    //MARK: - Notifications
    func didFinishGettingNotifications(notificationsCount: String?)
}
