//
//  FeedRouter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 01/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RealmSwift
import Firebase

open class FeedRouter: NSObject, FeedWireframeProtocol {

    weak var viewController: UIViewController?
    
    public static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = Home_RedSocial(nibName: "FeedViewController", bundle: Bundle(for: Home_RedSocial.self))
        let interactor = FeedInteractor()
        let router = FeedRouter()
        let presenter = FeedPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    //MARK: - ShowPostDetail
    func showPostDetail(navController: UINavigationController?, post: PublicationRealm) {
        guard let vc = DetailPostRouter.createModule() as? DetailPostViewController else { return }
        vc.post = post
        navController?.pushViewController(vc, animated: true)
    }
    
    //MARK: - ShowComments
//    func showComments(postId: Int) {
//        let vc = CommentsRouter.createModule() as! CommentsViewController
//        vc.postId = postId
//        vc.isKBFocused = false
//        vc.modalPresentationStyle = .custom
//        vc.transitioningDelegate = self
//        viewController?.present(vc, animated: true)
//    }
    
    //MARK: - ShowEditPost
//    func showEditPost(postId: Int, content: String, nombreGrupo: String, imagenGrupo: String) {
//        let vc = EditPostModalRouter.createModule() as! EditPostModalViewController
//        vc.postId = postId
//        vc.content = content
//        vc.groupName = nombreGrupo
//        vc.groupImage = imagenGrupo
//        vc.modalPresentationStyle = .custom
//        vc.transitioningDelegate = self
//        viewController?.present(vc, animated: true)
//    }
    
    //MARK: - ShowWhoPublishes
    func showNewPost() {
        guard let vc = CreatePostRouter.createModule() as? RedSocial_CrearPost else { return }
        vc.hasManyGroups = false
        vc.modalPresentationStyle = .fullScreen
        viewController?.present(vc, animated: true)
    }
    
    func showEditPost(post: PublicationRealm, editPost: Bool) {
        // GGG4
        guard let vc = CreatePostRouter.createModule() as? RedSocial_CrearPost else { return }
        vc.hasManyGroups = false
        vc.editPost = true
        vc.postInformation = post
        vc.modalPresentationStyle = .pageSheet
        viewController?.present(vc, animated: true)
    }
    
    func showNewEditPost(post: Posts, editPost: Bool) {
        guard let vc = CreatePostRouter.createModule() as? RedSocial_CrearPost else { return }
        vc.hasManyGroups = false
        vc.editPost = true
        vc.newPostsInfo = post
        vc.modalPresentationStyle = .pageSheet
        viewController?.present(vc, animated: true)
    }
    
    func showActionsSelected(post: PublicationRealm, strSelected: String) {
        guard let vc = SNCommenctsRoute.createNewModule() as? CommentsViewController else { return }
        let feed = FeedRouter.createModule() as! Home_RedSocial
        let navigationController = UINavigationController(rootViewController: feed)
        navigationController.navigationBar.isHidden = true
        navigationController.pushViewController(vc, animated: true)
        
    }
    
    
    //MARK: - Methods
    private func retrieveFromRealm() -> [GroupRealm]? {
        let results = RealmManager.fetchData(object: GroupRealm.self)
        return results
    }
}

//MARK: - UIViewControllerTransitioningDelegate
extension FeedRouter: UIViewControllerTransitioningDelegate {
    public func presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController? {
        ModalPresentationController(presentedViewController: presented, presenting: presenting)
    }
}
