//
//  MassesViewController.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
//Primer push a Sergio
import UIKit

class MassesViewController: UIViewController, MassesViewProtocol {

	var presenter: MassesPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
    }

}
