//
//  MassesInteractor.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MassesInteractor: MassesInteractorProtocol {

    weak var presenter: MassesPresenterProtocol?
}
