//
//  MassesProtocols.swift
//  EncuentroCatolicoMasses
//
//  Created Diego Martinez on 02/03/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MassesWireframeProtocol: class {

}
//MARK: Presenter -
protocol MassesPresenterProtocol: class {

}

//MARK: Interactor -
protocol MassesInteractorProtocol: class {

  var presenter: MassesPresenterProtocol?  { get set }
}

//MARK: View -
protocol MassesViewProtocol: class {

  var presenter: MassesPresenterProtocol?  { get set }
}
