//
//  InitViewController.swift
//  EncuentroCatolico
//
//  Created Diego Martinez on 04/02/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import EncuentroCatolicoHome
import EncuentroCatolicoLogin
//import EncuentroCatolicoNews

class InitViewController: UIViewController, InitViewProtocol {
    
    var presenter: InitPresenterProtocol?
    
    //MARK: - View
    var InitComponents: InitComponents! {
        guard isViewLoaded else { return nil }
        return (view as! InitComponents)
    }
    
    //MARK: - Life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        
        let defaults = UserDefaults.standard
        let nombre = defaults.string(forKey: "nombre") ?? ""
    
//            if nombre != "" {
//                openHome()
//            } else {
//                openLogin()
//            }
    }
    
    func openLogin(){
        let view = LoginRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
    
    func openOnboarding(){
        let view = Vista1WireFrame.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
    
    func openHome(){
        let instance = FirebaseManager.shared.getSNFirebaseInstance()
        let view = SocialNetwork.openSocialNetowrk(firebaseApp: instance)
        view.modalPresentationStyle = .fullScreen
        self.present(view, animated: true)
    }
    
}
