//
//  ImagePresenterProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 17/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ImagePresenterWireframeProtocol: class {
    
}

//MARK: Presenter -
protocol ImagePresenterPresenterProtocol: class {

}

//MARK: Interactor -
protocol ImagePresenterInteractorProtocol: class {
    
    var presenter: ImagePresenterPresenterProtocol?  { get set }
}

//MARK: View -
protocol ImagePresenterViewProtocol: class {
    
    var presenter: ImagePresenterPresenterProtocol?  { get set }
}
