//
//  ImagePresenterPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 17/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class ImagePresenterPresenter: ImagePresenterPresenterProtocol {

    weak private var view: ImagePresenterViewProtocol?
    var interactor: ImagePresenterInteractorProtocol?
    private let router: ImagePresenterWireframeProtocol

    init(interface: ImagePresenterViewProtocol, interactor: ImagePresenterInteractorProtocol?, router: ImagePresenterWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
