//
//  ProfileUserInfoPresenter.swift
//  EncuentroCatolicoProfile
//
//  Created Desarrollo on 07/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileUserInfoPresenter: ProfileUserInfoPresenterProtocol {

    weak private var view: ProfileUserInfoViewProtocol?
    var interactor: ProfileUserInfoInteractorProtocol?
    private let router: ProfileUserInfoWireframeProtocol

    init(interface: ProfileUserInfoViewProtocol, interactor: ProfileUserInfoInteractorProtocol?, router: ProfileUserInfoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getProvidedServices() {
        interactor?.requestServices()
    }
    
//    func getResponse(errores: ErroresServidorProfile, data: ProvidedServices?) {
//            DispatchQueue.main.async {
//                switch errores {
//                case .ErrorInterno:
//                    let msg = ["titulo":"Error", "cuerpo": "Error en el servidor"]
//                    self.view?.mostrarMSG(dtcAlerta: msg)
//                case .ErrorServidor:
//                    let msg = ["titulo":"Error", "cuerpo": "Error en la aplicación"]
//                    self.view?.mostrarMSG(dtcAlerta: msg)
//                case .OK:
//                    self.view?.loadCatalog(data: data!)
//                }
//            }
//    }
    
    

}
