//
//  ProfileUserInfoProtocols.swift
//  EncuentroCatolicoProfile
//
//  Created Desarrollo on 07/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProfileUserInfoWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol ProfileUserInfoPresenterProtocol: class {
//    func getResponse(errores: ErroresServidorProfile, data: ProvidedServices?)
    func getProvidedServices()
} 

//MARK: Interactor -
protocol ProfileUserInfoInteractorProtocol: class {
    var presenter: ProfileUserInfoPresenterProtocol?  { get set }
    func requestServices()
}

//MARK: View -
protocol ProfileUserInfoViewProtocol: class {
    
    var presenter: ProfileUserInfoPresenterProtocol?  { get set }
    
    func mostrarMSG(dtcAlerta: [String:String])
//    func loadCatalog(data: ProvidedServices)
}
