//
//  ProfileUserInfoInteractor.swift
//  EncuentroCatolicoProfile
//
//  Created Desarrollo on 07/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileUserInfoInteractor: ProfileUserInfoInteractorProtocol {

    weak var presenter: ProfileUserInfoPresenterProtocol?
    
    func requestServices() {
        guard let endpoint: URL = URL(string: "\(APIType.shared.User())/catalog/provided-services") else {
            print("Error formando url")
//            self.presenter?.getResponse(errores: ErroresServidorProfile.ErrorServidor, data: nil)
            return
        }
        
        var request = URLRequest(url: endpoint)
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        let tksession = UserDefaults.standard.string(forKey: "idToken")
        request.setValue("Bearer \( tksession ?? "")", forHTTPHeaderField: "Authorization")
        request.httpMethod = "GET"
        
        let tarea = URLSession.shared.dataTask(with: request) { data, response, error in
            
            if error != nil {
                print("Hubo un error")
                return
            }
//
//            if (response as! HTTPURLResponse).statusCode == 200 {
//                let catalogResponse: ProvidedServices? = try? JSONDecoder().decode(ProvidedServices.self, from: data!)
//                self.presenter?.getResponse(errores: ErroresServidorProfile.OK, data: catalogResponse)
//            } else {
//                self.presenter?.getResponse(errores: ErroresServidorProfile.ErrorServidor, data: nil)
//            }
        }
        tarea.resume()
        
    }
}
