//
//  DetailPostPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 06/09/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RealmSwift

public class DetailPostPresenter: DetailPostPresenterProtocol {

    weak private var view: DetailPostViewProtocol?
    var interactor: DetailPostInteractorProtocol?
    private let router: DetailPostWireframeProtocol
    
    init(interface: DetailPostViewProtocol, interactor: DetailPostInteractorProtocol?, router: DetailPostWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - Comments
//    func getComments(postId: Int, isFromRefresh: Bool) {
//        interactor?.getComments(postId: postId, isFromRefresh: isFromRefresh)
//    }
//
//    func didFinishGettingComments(comments: Comments, pages: Int, total: Int, isFromRefresh: Bool) {
//        view?.didFinishGettingComments(comments: comments, pages: pages, total: total, isFromRefresh: isFromRefresh)
//    }
//
//    func didFinishGettingCommentsWithErrors(error: SocialNetworkErrors) {
//        view?.didFinishGettingCommentsWithErrors(error: error)
//    }
    
    //MARK: - TopReactions
    func getTopReactions(postId: Int) {
        interactor?.getTopReactions(postId: postId)
    }
    
    func didFinishGettingTopReactions(topReactions: TopReactions) {
        view?.didFinishGettingTopReactions(topReactions: topReactions)
    }
    
    func didFinishGettingTopReactionsWithErrors(error: SocialNetworkErrors) {
        view?.didFinishGettingTopReactionsWithErrors(error: error)
    }
    
    //MARK: - Comments
//    func showComments(postId: Int, isKBFocused: Bool) {
//        router.showComments(postId: postId, isKBFocused: isKBFocused)
//    }
    
    //MARK: - ShowReactions
    func showReactions(postId: Int) {
        router.showReactions(postId: postId)
    }
    
    //MARK: - ShowImages
    func showImages(navController: UINavigationController?, media: List<MediaRealm>) {
        router.showImages(navController: navController, media: media)
    }
}
