//
//  VideoPresenterPresenter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 29/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class VideoPresenterPresenter: VideoPresenterPresenterProtocol {

    weak private var view: VideoPresenterViewProtocol?
    var interactor: VideoPresenterInteractorProtocol?
    private let router: VideoPresenterWireframeProtocol

    init(interface: VideoPresenterViewProtocol, interactor: VideoPresenterInteractorProtocol?, router: VideoPresenterWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
