//
//  VideoPresenterRouter.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 29/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AVKit

public class VideoPresenterRouter: VideoPresenterWireframeProtocol {
    
    weak var viewController: AVPlayerViewController?
    
    static func createModule() -> AVPlayerViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = VideoPresenterViewController(nibName: "VideoPresenterViewController", bundle: Bundle.local)
        let interactor = VideoPresenterInteractor()
        let router = VideoPresenterRouter()
        let presenter = VideoPresenterPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
