//
//  VideoPresenterProtocols.swift
//  zeus-ios-sdk-new-social-network
//
//  Created Miguel Angel Vicario Flores on 29/10/20.
//  Copyright © 2020 Gabriel Briseño. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol VideoPresenterWireframeProtocol: class {

}

//MARK: Presenter -
protocol VideoPresenterPresenterProtocol: class {

}

//MARK: Interactor -
protocol VideoPresenterInteractorProtocol: class {
    
    var presenter: VideoPresenterPresenterProtocol?  { get set }
}

//MARK: View -
protocol VideoPresenterViewProtocol: class {

  var presenter: VideoPresenterPresenterProtocol?  { get set }
}
