//
//  ScheduleMassInteractor.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 28/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScheduleMassInteractor: ScheduleMassInteractorProtocol {

    weak var presenter: ScheduleMassPresenterProtocol?
}
