//
//  ScheduleMassProtocols.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 28/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ScheduleMassWireframeProtocol: class {

}
//MARK: Presenter -
protocol ScheduleMassPresenterProtocol: class {

}

//MARK: Interactor -
protocol ScheduleMassInteractorProtocol: class {

  var presenter: ScheduleMassPresenterProtocol?  { get set }
}

//MARK: View -
protocol ScheduleMassViewProtocol: class {

  var presenter: ScheduleMassPresenterProtocol?  { get set }
}
