//
//  ScheduleMassRouter.swift
//  EncuentroCatolicoServices
//
//  Created Desarrollo on 28/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class ScheduleMassRouter: ScheduleMassWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule(location: Assigned) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ScheduleMassViewController(nibName: "ScheduleMassViewController", bundle: Bundle.init(identifier: "mx.arquidiocesis.EncuentroCatolicoServices"))
        let interactor = ScheduleMassInteractor()
        let router = ScheduleMassRouter()
        let presenter = ScheduleMassPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        view.location = location
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
