//
//  CategoriesRouter.swift
//  EncuentroCatolicoVirtualLibrary
//
//  Created Desarrollo on 20/04/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class CategoriesRouter: CategoriesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static public func createModule(category: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let storyboard = UIStoryboard(name: "Categories", bundle: Bundle(for: CategoriesView.self))
        let view:CategoriesView = storyboard.instantiateViewController(withIdentifier: "CategoriesView") as! CategoriesView
        let interactor = CategoriesInteractor()
        let router = CategoriesRouter()
        let presenter = CategoriesPresenter(interface: view, interactor: interactor, router: router)
        
        view.contentcategory = category
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
