//
//  LivePresenter.swift
//  EncuentroCatolicoLive
//
//  Created Diego Martinez on 25/02/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LivePresenter: LivePresenterProtocol {
    
    weak private var view: LiveViewProtocol?
    var interactor: LiveInteractorProtocol?
    private let router: LiveWireframeProtocol

    init(interface: LiveViewProtocol, interactor: LiveInteractorProtocol?, router: LiveWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getData() {
        interactor?.requestData()
    }
    
    func getResponse(data: [LiveModel], response: HTTPURLResponse) {
        
        DispatchQueue.main.async {
            if response.statusCode == 200 {
                self.view?.loadContent(data: data)
            }else{
                self.view?.failRequestData(message: "")
            }
        }
    }
    
}
