//
//  LiveProtocols.swift
//  EncuentroCatolicoLive
//
//  Created Diego Martinez on 25/02/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LiveWireframeProtocol: class {

}
//MARK: Presenter -
protocol LivePresenterProtocol: class {
    func getData()
    func getResponse(data: [LiveModel], response: HTTPURLResponse)
}

//MARK: Interactor -
protocol LiveInteractorProtocol: class {

  var presenter: LivePresenterProtocol?  { get set }
    func requestData()
    
}

//MARK: View -
protocol LiveViewProtocol: class {

  var presenter: LivePresenterProtocol?  { get set }
    func loadContent(data: [LiveModel])
    func failRequestData(message: String)
}
